FROM ubuntu:14.04
MAINTAINER m<since92x@gmail.com>
RUN	sed -i 's/http:\/\/archive\.ubuntu\.com\/ubuntu\//http:\/\/mirrors\.163\.com\/ubuntu\//g' /etc/apt/sources.list && \
	apt-get update && apt-get install -y --no-install-recommends \
	ca-certificates curl wget bzr git mercurial openssh-client subversion procps autoconf \
	automake bzip2 file g++ gcc imagemagick libbz2-dev libc6-dev libcurl4-openssl-dev \
	libdb-dev libevent-dev libffi-dev libgdbm-dev libgeoip-dev libglib2.0-dev libjpeg-dev \
	libkrb5-dev liblzma-dev libmagickcore-dev libmagickwand-dev libmysqlclient-dev libncurses-dev \
	libpng-dev libpq-dev libreadline-dev libsqlite3-dev libssl-dev libtool libwebp-dev libxml2-dev \
	libxslt-dev libyaml-dev make patch xz-utils zlib1g-dev screen build-essential vim-gnome htop \
	python-software-properties software-properties-common && \
	apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
CMD ["/bin/bash"]

